node {

    stage('Checkout SCM') {
        checkout scm
    }
    
    // Permorming Install and Lint
      stage('Install') {
        sh label:
          'Running npm install',
        script: '''
          node --version
          cd hello-world-node
          npm install
        '''
      }

    stage ('Build') {

        sh label:
          'Running npm run build',
        script: '''
          node --version
          cd hello-world-node
          npm run build
        '''
      }
}
